### ISSUE TITLE
Sending meassurements over USB

### ISSUE THREAD

**Issue by hoijui** [wagiminator/ATtiny85-USB-Tester#1]
Can this be extended to do that, and would it need hardware adjustments or only in the firmware?

This similar project seems to be capable of doing that:

- [x] assembly video: https://www.youtube.com/watch?v=1q8gbx8BXxM
- [x] firmware/software: https://github.com/inflex/pld-usbc-meter/tree/main
- [ ] hardware: not available (I think), but ...  think it is quite similar to this project

**Comment by wagiminator** [comment]
Hi, this requires changes to the hardware. For a sensible implementation, a different microcontroller should be chosen anyway and the whole thing should be completely redesigned.

**Comment by hoijui** [comment]
oook.
thanks a lot for the swift answer! :-)
for what I care, you can close the issue.
