### ISSUE TITLE
What typeface you are using?

### ISSUE THREAD

**Issue by nehcoab** [wagiminator/ATtiny85-USB-Tester#4]
Hi, Steven. Can you tell me what typeface you are using on the OLED screen? I want to use it in my project.

![1](https://github.com/user-attachments/assets/63327661-80c1-4e10-be0e-bea7301d8fde)

**Comment by wagiminator** [comment]
Hi, the font is literally hand-drawn on a piece of graph paper and then bitwise calculated in my head. The corresponding values are in the source code. It includes only the numbers and letters used in the application. In short, the font is incomplete and therefore not suitable for use in other projects.

**Comment by baochen831** [comment]
Wow, it's your own design? No wonder I couldn't find it after searching for a long time. I think it displays well, at least on a 0.91-inch OLED screen. It might be worth considering to design a full set of fonts, that would be an excellent project.

**Comment by nehcoab** [comment]
Wow, it's your own design? No wonder I couldn't find it after searching for a long time. I think it displays well, at least on a 0.91-inch OLED screen. It might be worth considering to design a full set of fonts, that would be an excellent project.

**Comment by wagiminator** [comment]
Well, my primary interest is not in font design; it was more of an unwelcome necessity here. Therefore, I'll probably only create a complete character set if I need it for one of my projects.
